### ISSUE TITLE
New Feature Tracker

### ISSUE THREAD

**Issue by matthewcarbone** [matthewcarbone/gpax#3]
In this issue, I'll keep track of things I want to do with this fork.

# Priority
Previous features we still need to re-implement. Based on manuscript abstract.

- [ ] Multi-fidelity GPs
- [ ] Multi-task GPs (might be the same as above)
- [ ] Learnable uncertainty in the inputs
- [ ] Heteroskedastic GPs
- [ ] DKL (single and multi-fidelity)

# Logged
- [x] Add input and output transforms for the GP. I.e., input features (and potentially targets) can be seamlessly and without user intervention, scaled to some other distribution, e.g. a fixed range in the d-dimension unit box, or a to a normal distribution. This should be compatible with acquisition functions at least.
- [x] ~~Make the transforms above compatible with kernel priors? Possibly not necessary since one can simply set the kernel priors in the transformed space pretty easily, since that transformed space is usually roughly between -1 and 1 or close nearby (#2).~~ (**Cancelled - we'll do this later**)
- [x] Add global random state so we don't have to pass `rng_key` to every function.
- [x] Add experiment abstraction for quick testing and retrieval of data.
- [x] Standardize the `fit` API so `fit` looks the same irrespective of the type of GP (start with fully Bayesian and VI)
- [x] ~~Implement LOVE algorithm (#1). This could help address the batch sampling problem (https://github.com/ziatdinovmax/gpax/issues/116).~~ (**Cancelled - it turns out this doesn't actually solve the problem I wanted to, might re-implement later but shelved for now**)
- [x] Implement parallel acquisition for EI and UCB.
- [x] Re-implement Bayesian prior mean functions.
